---
platforms:
  ubuntu2204:
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  ubuntu2004:
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  macos_arm64:
    build_targets:
      - //...
    test_targets:
      - //...
      # The python version doesn't support macos arm64
      - "-//:py_bazelisk_test"
      - "-//:py3_bazelisk_test"
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  windows:
    build_targets:
      - //...
    test_targets:
      - //...
      # Windows doesn't have a `python3` executable on PATH.
      - -//:py3_bazelisk_test
    test_flags:
      - --flaky_test_attempts=1
      - --test_env=PATH
      - --test_env=PROCESSOR_ARCHITECTURE
      - --test_output=streamed
