load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "httputil",
    srcs = ["httputil.go"],
    importpath = "github.com/bazelbuild/bazelisk/httputil",
    visibility = ["//visibility:public"],
)